version: "3"
services:
  app:
    build: ./app
    image: treadfyi/tread-app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
  tread-realtime:
    build: ./tread-realtime
    command: yarn dev
    image: treadfyi/tread-realtime
    ports:
      - "8080:80"
    volumes:
      - ./tread-realtime:/tread-realtime
